module.exports = function(ngModule) {
    // filter
    require("./filter/date-filter")(ngModule);
    //utils
    require("./utils/promise-factory")(ngModule);
    require("./utils/datepicker-pattern-directive")(ngModule);
    require("./utils/template-content-directive")(ngModule);
    require("./utils/float-thead-directive")(ngModule);
    require("./utils/bytes-maxlength-directive")(ngModule);
    require("./utils/date-compare-directive")(ngModule);
    require("./utils/util-service")(ngModule);
    require("./utils/analytics-service")(ngModule);
    //authorization
    require("./authorization/mtk-hash-provider")(ngModule);
    require("./authorization/authorization-service")(ngModule);
    //ui-widgets
    require("./ui-widgets/switch/switch-directive")(ngModule);
    require("./ui-widgets/modal-alert/modal-service")(ngModule);
    require("./ui-widgets/modal-alert/modal-alert-directive")(ngModule);
    require("./ui-widgets/img-file-input/img-file-input-directive")(ngModule);
    require("./ui-widgets/img-file-input/show-canvas-directive")(ngModule);
    require("./ui-widgets/img-crop-input/img-crop-input-directive")(ngModule);
    require("./ui-widgets/enterSubmit/enterSubmit-directive")(ngModule);
    require("./ui-widgets/pic-fileupload/pic-fileupload-directive")(ngModule);
    require("./ui-widgets/voice-fileupload/voice-fileupload-directive")(ngModule);
    require("./ui-widgets/voice-play/voice-play-directive")(ngModule);
    require("./ui-widgets/video-fileupload/video-fileupload-directive")(ngModule);
    require("./ui-widgets/video-play/video-play-directive")(ngModule);
    require("./ui-widgets/message-editor/message-editor-directive")(ngModule);
    require("./ui-widgets/message-editor/modal-pic-ctrl")(ngModule);
    require("./ui-widgets/message-editor/modal-pictext-ctrl")(ngModule);
    require("./ui-widgets/message-editor/modal-voice-ctrl")(ngModule);
    require("./ui-widgets/message-editor/modal-video-ctrl")(ngModule);
    require("./ui-widgets/message-editor/message-pictext-directive")(ngModule);
    require("./ui-widgets/message-editor/message-voice-directive")(ngModule);
    require("./ui-widgets/message-editor/message-voice-modal-ctrl")(ngModule);
    require("./ui-widgets/message-editor/message-video-directive")(ngModule);
    require("./ui-widgets/message-editor/message-video-modal-ctrl")(ngModule);
    require("./ui-widgets/message-editor/message-pic-directive")(ngModule);
    require("./ui-widgets/message-editor/message-pic-modal-ctrl")(ngModule);
    require("./ui-widgets/pictext-input/pictext-input-directive")(ngModule);
    require("./ui-widgets/pictext-textarea/pictext-textarea-directive")(ngModule);
    require("./ui-widgets/richeditor/richeditor-directive")(ngModule);
    require("./ui-widgets/loading/loading-directive")(ngModule);
    //page-services
    require("./page-services/channel-service")(ngModule);
    require("./page-services/account-service")(ngModule);
    require("./page-services/fansinfo-service")(ngModule);
    require("./page-services/appinfo-service")(ngModule);
    require("./page-services/module-service")(ngModule);
    require("./page-services/systemcode-service")(ngModule);
    require("./page-services/selfmenu-service")(ngModule);
    require("./page-services/push-service")(ngModule);
    require("./page-services/message-service")(ngModule);
    require("./page-services/mediagroup-service")(ngModule);
    require("./page-services/image-service")(ngModule);
    require("./page-services/information-service")(ngModule);
    require("./page-services/pictext-service")(ngModule);
    require("./page-services/voice-service")(ngModule);
    require("./page-services/video-service")(ngModule);
    require("./page-services/usergroup-service")(ngModule);
    require("./page-services/category-service")(ngModule);
    require("./page-services/review-service")(ngModule);
    require("./page-services/systemannounce-service")(ngModule);
    require("./page-services/channelannounce-service")(ngModule);
    require("./page-services/agent-service")(ngModule);
    require("./page-services/applytest-service")(ngModule);
};
